name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Restore Cache
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
        
      - name: Detekt
        run: ./gradlew detektMain

      - name: Instrumentation Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedDebugAndroidTest
